# Generated by Django 5.0.6 on 2024-07-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category2', models.CharField(choices=[('EKONOM', 'Ekonom'), ('KOMFORT', 'Komfort'), ('LYUKS', 'Lyuks')], max_length=7)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aviakompaniya', models.CharField(max_length=50)),
                ('davomiyligi', models.IntegerField()),
                ('ovqatlanish', models.IntegerField()),
                ('viza_kiritilgan', models.BooleanField()),
                ('tibbiy_yordam', models.BooleanField()),
                ('tajribali_yolboshchi', models.BooleanField()),
                ('zamzam_suvi', models.BooleanField()),
                ('jilet', models.BooleanField()),
                ('sumka_va_nishon', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.category')),
            ],
        ),
    ]
